name: ryu1kn/csv-writer
on:
  push:
    branches:
    - "**/*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.0.0
    - uses: actions/setup-node@v3.8.1
      with:
        cache: npm
        node-version: '14.5'
    - run: npm install
    - run: npm run lint
    - run: npm run test:it
    - run: npm run coverage

    # FIXME: coveralls fails to report the result
    #- run: cat coverage/lcov.info | node_modules/.bin/coveralls

    # FIXME: CodeClimate fails to analyze/report
    #- run: |-
    #    curl -L https://github.com/codeclimate/codeclimate/archive/master.tar.gz | tar xvz
    #    cd codeclimate-* && sudo make install
    #    codeclimate analyze
    #  env:
    #    CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
